/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
/**
 *
 * @author USER
 */
public class WeatherAppGUI extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
    /**
     * Creates new form WeatherAppGUI
     */
    public WeatherAppGUI() {
        initComponents();
        setupTable();
        loadFavoritesToComboBox();
        setLocationRelativeTo(null); // Center window
    }
    
    private void setupTable() {
        String[] columns = {"Kota", "Negara", "Suhu (°C)", "Deskripsi", 
                           "Kelembaban (%)", "Angin (m/s)", "Kondisi", "Waktu"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tidak bisa diedit
            }
        };
        tableWeatherHistory.setModel(tableModel);
    }
    
    private void loadFavoritesToComboBox() {
        cmbFavorites.removeAllItems();
        cmbFavorites.addItem("-- Pilih Kota Favorit --");
        
        List<String> favorites = FavoriteCities.loadFavorites();
        for (String city : favorites) {
            cmbFavorites.addItem(city);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        lblInputCity = new javax.swing.JLabel();
        txtCityInput = new javax.swing.JTextField();
        btnCheckWeather = new javax.swing.JButton();
        lblFavorites = new javax.swing.JLabel();
        cmbFavorites = new javax.swing.JComboBox<>();
        btnAddFavorite = new javax.swing.JButton();
        btnRemoveFavorite = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(10000, 10));
        panelWeatherResult = new javax.swing.JPanel();
        lblWeatherHeader = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblWeatherIcon = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblHumidity = new javax.swing.JLabel();
        lblWindSpeed = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(10000, 10));
        panelHistory = new javax.swing.JPanel();
        lblHistoryHeader = new javax.swing.JLabel();
        scrollPaneHistory = new javax.swing.JScrollPane();
        tableWeatherHistory = new javax.swing.JTable();
        panelButtons = new javax.swing.JPanel();
        btnSaveCSV = new javax.swing.JButton();
        btnLoadHistory = new javax.swing.JButton();
        btnClearHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Cek Cuaca - Weather App");
        setPreferredSize(new java.awt.Dimension(870, 1100));
        setResizable(false);

        panelHeader.setBackground(new java.awt.Color(66, 153, 225));
        panelHeader.setPreferredSize(new java.awt.Dimension(850, 80));
        panelHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Aplikasi Cek Cuaca");
        panelHeader.add(lblTitle, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelHeader, java.awt.BorderLayout.NORTH);

        panelMain.setBackground(new java.awt.Color(240, 244, 255));
        panelMain.setLayout(new javax.swing.BoxLayout(panelMain, javax.swing.BoxLayout.Y_AXIS));

        panelInput.setBackground(new java.awt.Color(237, 242, 247));
        panelInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 224), 2), javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 20)));
        panelInput.setMaximumSize(new java.awt.Dimension(10000, 160));
        panelInput.setPreferredSize(new java.awt.Dimension(830, 160));
        panelInput.setLayout(new java.awt.GridBagLayout());

        lblInputCity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInputCity.setForeground(new java.awt.Color(74, 85, 104));
        lblInputCity.setText("Masukkan Nama Kota:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(lblInputCity, gridBagConstraints);

        txtCityInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCityInput.setPreferredSize(new java.awt.Dimension(320, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(txtCityInput, gridBagConstraints);

        btnCheckWeather.setBackground(new java.awt.Color(72, 187, 120));
        btnCheckWeather.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCheckWeather.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckWeather.setText("Cek Cuaca");
        btnCheckWeather.setBorderPainted(false);
        btnCheckWeather.setOpaque(true);
        btnCheckWeather.setPreferredSize(new java.awt.Dimension(140, 35));
        btnCheckWeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckWeatherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(btnCheckWeather, gridBagConstraints);

        lblFavorites.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFavorites.setForeground(new java.awt.Color(74, 85, 104));
        lblFavorites.setText("Atau Pilih dari Favorit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(lblFavorites, gridBagConstraints);

        cmbFavorites.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbFavorites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFavorites.setPreferredSize(new java.awt.Dimension(280, 35));
        cmbFavorites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFavoritesItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(cmbFavorites, gridBagConstraints);

        btnAddFavorite.setBackground(new java.awt.Color(66, 153, 225));
        btnAddFavorite.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddFavorite.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFavorite.setText("Tambah Favorit");
        btnAddFavorite.setBorderPainted(false);
        btnAddFavorite.setOpaque(true);
        btnAddFavorite.setPreferredSize(new java.awt.Dimension(150, 35));
        btnAddFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavoriteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(btnAddFavorite, gridBagConstraints);

        btnRemoveFavorite.setBackground(new java.awt.Color(245, 101, 101));
        btnRemoveFavorite.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRemoveFavorite.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveFavorite.setText("Hapus Favorit");
        btnRemoveFavorite.setBorderPainted(false);
        btnRemoveFavorite.setOpaque(true);
        btnRemoveFavorite.setPreferredSize(new java.awt.Dimension(150, 35));
        btnRemoveFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFavoriteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(btnRemoveFavorite, gridBagConstraints);

        panelMain.add(panelInput);
        panelMain.add(filler1);

        panelWeatherResult.setBackground(new java.awt.Color(255, 255, 255));
        panelWeatherResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 224), 2));
        panelWeatherResult.setMaximumSize(new java.awt.Dimension(10000, 300));
        panelWeatherResult.setPreferredSize(new java.awt.Dimension(830, 300));
        panelWeatherResult.setLayout(new java.awt.GridBagLayout());

        lblWeatherHeader.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblWeatherHeader.setForeground(new java.awt.Color(45, 55, 72));
        lblWeatherHeader.setText("Informasi Cuaca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelWeatherResult.add(lblWeatherHeader, gridBagConstraints);

        lblCityName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(43, 108, 176));
        lblCityName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCityName.setText("Jakarta, Indonesia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelWeatherResult.add(lblCityName, gridBagConstraints);

        lblWeatherIcon.setBackground(new java.awt.Color(247, 250, 252));
        lblWeatherIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeatherIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)));
        lblWeatherIcon.setOpaque(true);
        lblWeatherIcon.setPreferredSize(new java.awt.Dimension(120, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelWeatherResult.add(lblWeatherIcon, gridBagConstraints);

        lblTemperature.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTemperature.setForeground(new java.awt.Color(229, 62, 62));
        lblTemperature.setText("32.5°C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelWeatherResult.add(lblTemperature, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(74, 85, 104));
        lblDescription.setText("Deskripsi: Cerah Berawan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelWeatherResult.add(lblDescription, gridBagConstraints);

        lblHumidity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHumidity.setForeground(new java.awt.Color(74, 85, 104));
        lblHumidity.setText("Kelembaban: 75%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelWeatherResult.add(lblHumidity, gridBagConstraints);

        lblWindSpeed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblWindSpeed.setForeground(new java.awt.Color(74, 85, 104));
        lblWindSpeed.setText("Kecepatan Angin: 5.2 m/s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelWeatherResult.add(lblWindSpeed, gridBagConstraints);

        panelMain.add(panelWeatherResult);
        panelMain.add(filler2);

        panelHistory.setBackground(new java.awt.Color(255, 255, 255));
        panelHistory.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        panelHistory.setMaximumSize(new java.awt.Dimension(10000, 450));
        panelHistory.setPreferredSize(new java.awt.Dimension(830, 450));
        panelHistory.setLayout(new java.awt.BorderLayout());

        lblHistoryHeader.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHistoryHeader.setForeground(new java.awt.Color(45, 55, 72));
        lblHistoryHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistoryHeader.setText("Riwayat Pengecekan Cuaca");
        panelHistory.add(lblHistoryHeader, java.awt.BorderLayout.NORTH);

        scrollPaneHistory.setPreferredSize(new java.awt.Dimension(800, 320));

        tableWeatherHistory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableWeatherHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableWeatherHistory.setRowHeight(30);
        tableWeatherHistory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneHistory.setViewportView(tableWeatherHistory);

        panelHistory.add(scrollPaneHistory, java.awt.BorderLayout.CENTER);

        panelButtons.setPreferredSize(new java.awt.Dimension(830, 60));
        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btnSaveCSV.setBackground(new java.awt.Color(128, 90, 213));
        btnSaveCSV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSaveCSV.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCSV.setText("Simpan ke CSV");
        btnSaveCSV.setBorderPainted(false);
        btnSaveCSV.setOpaque(true);
        btnSaveCSV.setPreferredSize(new java.awt.Dimension(200, 40));
        btnSaveCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCSVActionPerformed(evt);
            }
        });
        panelButtons.add(btnSaveCSV);

        btnLoadHistory.setBackground(new java.awt.Color(56, 178, 172));
        btnLoadHistory.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLoadHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadHistory.setText("Muat Riwayat");
        btnLoadHistory.setBorderPainted(false);
        btnLoadHistory.setOpaque(true);
        btnLoadHistory.setPreferredSize(new java.awt.Dimension(200, 40));
        btnLoadHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadHistoryActionPerformed(evt);
            }
        });
        panelButtons.add(btnLoadHistory);

        btnClearHistory.setBackground(new java.awt.Color(237, 137, 54));
        btnClearHistory.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnClearHistory.setText("Hapus Semua");
        btnClearHistory.setBorderPainted(false);
        btnClearHistory.setOpaque(true);
        btnClearHistory.setPreferredSize(new java.awt.Dimension(200, 40));
        panelButtons.add(btnClearHistory);

        panelHistory.add(panelButtons, java.awt.BorderLayout.SOUTH);

        panelMain.add(panelHistory);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckWeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckWeatherActionPerformed
        String cityName = txtCityInput.getText().trim();
    
        if (cityName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan nama kota terlebih dahulu!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tampilkan loading
        btnCheckWeather.setEnabled(false);
        btnCheckWeather.setText("Memuat...");

        // Gunakan SwingWorker untuk async
        SwingWorker<WeatherData, Void> worker = new SwingWorker<WeatherData, Void>() {
            @Override
            protected WeatherData doInBackground() throws Exception {
                return WeatherAPI.getWeatherData(cityName);
            }

            @Override
            protected void done() {
                try {
                    WeatherData data = get();
                    displayWeatherData(data);
                    addToTable(data);

                    // Simpan otomatis ke CSV
                    FavoriteCities.saveWeatherToCSV(data);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(WeatherAppGUI.this, 
                        "Error: " + e.getMessage(), 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                } finally {
                    btnCheckWeather.setEnabled(true);
                    btnCheckWeather.setText("Cek Cuaca");
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnCheckWeatherActionPerformed

    private void btnAddFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavoriteActionPerformed
        String cityName = txtCityInput.getText().trim();
    
        if (cityName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan nama kota terlebih dahulu!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            FavoriteCities.saveFavorite(cityName);
            loadFavoritesToComboBox();
            JOptionPane.showMessageDialog(this, 
                cityName + " berhasil ditambahkan ke favorit!", 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "Error menyimpan favorit: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddFavoriteActionPerformed

    private void btnRemoveFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFavoriteActionPerformed
        String selected = (String) cmbFavorites.getSelectedItem();
    
        if (selected == null || selected.equals("-- Pilih Kota Favorit --")) {
            JOptionPane.showMessageDialog(this, 
                "Pilih kota dari ComboBox terlebih dahulu!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Hapus " + selected + " dari favorit?", 
            "Konfirmasi", 
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                FavoriteCities.removeFavorite(selected);
                loadFavoritesToComboBox();
                JOptionPane.showMessageDialog(this, 
                    selected + " berhasil dihapus dari favorit!", 
                    "Sukses", 
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, 
                    "Error menghapus favorit: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRemoveFavoriteActionPerformed

    private void cmbFavoritesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFavoritesItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selected = (String) cmbFavorites.getSelectedItem();
            if (selected != null && !selected.equals("-- Pilih Kota Favorit --")) {
                txtCityInput.setText(selected);
            }
        }
    }//GEN-LAST:event_cmbFavoritesItemStateChanged

    private void btnSaveCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCSVActionPerformed
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, 
                "Tidak ada data untuk disimpan!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, 
            "Data cuaca otomatis disimpan di file:\ndata/weather_history.csv", 
            "Informasi", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveCSVActionPerformed

    private void btnLoadHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadHistoryActionPerformed
        List<String[]> history = FavoriteCities.loadWeatherHistory();
    
        if (history.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Tidak ada riwayat cuaca yang tersimpan!", 
                "Informasi", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Clear table
        tableModel.setRowCount(0);

        // Load data
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        for (String[] row : history) {
            String time = sdf.format(new Date(Long.parseLong(row[7])));
            Object[] tableRow = {
                row[0], // City
                row[1], // Country
                row[2], // Temperature
                row[3], // Description
                row[4], // Humidity
                row[5], // Wind Speed
                row[6], // Condition
                time
            };
            tableModel.addRow(tableRow);
        }

        JOptionPane.showMessageDialog(this, 
            history.size() + " data berhasil dimuat!", 
            "Sukses", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLoadHistoryActionPerformed
    
    private void displayWeatherData(WeatherData data) {
        lblCityName.setText(data.getCityName() + ", " + data.getCountry());
        lblTemperature.setText(String.format("%.1f °C", data.getTemperature()));
        lblDescription.setText(capitalizeFirst(data.getDescription()));
        lblHumidity.setText("Kelembaban: " + data.getHumidity() + "%");
        lblWindSpeed.setText("Angin: " + data.getWindSpeed() + " m/s");

        // Load icon
        loadWeatherIcon(data.getIconName());
    }

    private void loadWeatherIcon(String iconName) {
        try {
            String path = "src/resources/" + iconName;
            File iconFile = new File(path);

            if (iconFile.exists()) {
                ImageIcon icon = new ImageIcon(path);
                Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                lblWeatherIcon.setIcon(new ImageIcon(img));
            } else {
                lblWeatherIcon.setText("(Icon tidak ditemukan)");
            }
        } catch (Exception e) {
            lblWeatherIcon.setText("(Error loading icon)");
        }
    }

    private String capitalizeFirst(String text) {
        if (text == null || text.isEmpty()) return text;
        return text.substring(0, 1).toUpperCase() + text.substring(1);
    }

    private void addToTable(WeatherData data) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String time = sdf.format(new Date(data.getTimestamp()));

        Object[] row = {
            data.getCityName(),
            data.getCountry(),
            String.format("%.1f", data.getTemperature()),
            capitalizeFirst(data.getDescription()),
            data.getHumidity(),
            data.getWindSpeed(),
            data.getWeatherCondition(),
            time
        };

        tableModel.insertRow(0, row); // Insert di baris pertama
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFavorite;
    private javax.swing.JButton btnCheckWeather;
    private javax.swing.JButton btnClearHistory;
    private javax.swing.JButton btnLoadHistory;
    private javax.swing.JButton btnRemoveFavorite;
    private javax.swing.JButton btnSaveCSV;
    private javax.swing.JComboBox<String> cmbFavorites;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFavorites;
    private javax.swing.JLabel lblHistoryHeader;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblInputCity;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeatherHeader;
    private javax.swing.JLabel lblWeatherIcon;
    private javax.swing.JLabel lblWindSpeed;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelWeatherResult;
    private javax.swing.JScrollPane scrollPaneHistory;
    private javax.swing.JTable tableWeatherHistory;
    private javax.swing.JTextField txtCityInput;
    // End of variables declaration//GEN-END:variables
}
